[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'everzet/phpfolding.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'mechatroner/rainbow_csv'
