[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = 'has("lua")'
hook_add = '''
runtime! hook/neocomplete.vim
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'everzet/phpfolding.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'szw/vim-tags'
